# Generated by Django 3.2 on 2023-05-14 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230514_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Слаг тега'),
            preserve_default=False,
        ),
    ]
